[scrolling]
history = 100000

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[font]
size = 14

[keyboard]
  [[keyboard.bindings]]
  key = "Tab"
  mods = "Control|Shift"
  action = "SelectPreviousTab"

  [[keyboard.bindings]]
  key = "Tab"
  mods = "Control"
  action = "SelectNextTab"

  [[keyboard.bindings]]
  key = "Left"
  mods = "Command"
  action = "SelectPreviousTab"

  [[keyboard.bindings]]
  key = "Right"
  mods = "Command"
  action = "SelectNextTab"

  [[keyboard.bindings]]
  key = "¥"
  chars = '\'

